// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ControlConfigWarp: typeof import('./schema-components/ControlConfigWarp.vue')['default']
    McContainer: typeof import('./material-components/McContainer/index.vue')['default']
    McTitle: typeof import('./material-components/McTitle/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchemaNumber: typeof import('./schema-components/SchemaNumber/index.vue')['default']
  }
}
